apiVersion: apps/v1
kind: Deployment
metadata:
   name: mysql-deployment
   labels:
     app: mysql-server
spec:
   replicas: 1
   selector:
     matchLabels:
        app: mysql-server
   strategy:
     type: Recreate
   template:
     metadata:
       labels:
         app: mysql-server
     spec:
       containers:
       - name: mysql-container
         image: mysql:5.6
         env:
         - name: MYSQL_DATABASE
           valueFrom:
             secretKeyRef:
                 name: mysql-db-url
                 key: database
         - name: MYSQL_USER
           valueFrom:
             secretKeyRef:
                 name: mysql-user-pass
                 key: username
         - name: MYSQL_ROOT_PASSWORD
           valueFrom:
             secretKeyRef:
                 name: mysql-root-pass
                 key: password
         - name: MYSQL_PASSWORD
           valueFrom:
             secretKeyRef:
                 name: mysql-user-pass
                 key: password
         - name: MYSQL_HOST
           valueFrom:
             secretKeyRef:
                 name: mysql-host
                 key: host
         ports:
         - containerPort: 3306
           name: mysql
         volumeMounts:
         - name: mysql-persistent-storage
           mountPath: /var/lib/mysql
       volumes:
       - name: mysql-persistent-storage
         persistentVolumeClaim:
            claimName: mysql-pv-claim
