apiVersion: v1
kind: PersistentVolume
metadata:
   name: mysql-pv
   labels:
     app: mysql-volume
spec:
   capacity:
     storage: 5Gi
   accessModes:
     - ReadWriteOnce
   storageClassName: standard
   hostPath:
     path: "/mnt/data"
