apiVersion: apps/v1
kind: Deployment
metadata:
 labels:
   app: app
 name: nginx-wp-dp
spec:
   replicas: 1
   selector:
    matchLabels:
      app: app
   strategy:
     type: Recreate
   template:
     metadata:
       labels:
          app: app
     spec:
       containers:
       - name: nginx-container
         image: nginx:latest
         env:
         - name: MYSQL_DATABASE
           valueFrom:
             secretKeyRef:
                 name: mysql-db-url
                 key: database
         - name: MYSQL_USER
           valueFrom:
             secretKeyRef:
                 name: mysql-user-pass
                 key: username
         - name: MYSQL_ROOT_PASSWORD
           valueFrom:
             secretKeyRef:
                 name: mysql-root-pass
                 key: password
         - name: MYSQL_PASSWORD
           valueFrom:
             secretKeyRef:
                 name: mysql-user-pass
                 key: password
         - name: MYSQL_HOST
           valueFrom:
             secretKeyRef:
                 name: mysql-host
                 key: host
         volumeMounts:
         - name: shared-files
           mountPath: /var/www/html
         - name: nginx-config-volume
           mountPath: /etc/nginx/nginx.conf
           subPath: nginx.conf
         ports:
         - containerPort: 80
           name: http
           protocol: TCP
       - name: php-fpm-container
         image: wordpress:php7.2-fpm
         env:
         - name: MYSQL_DATABASE
           valueFrom:
             secretKeyRef:
                name: mysql-db-url
                key: database
         - name: MYSQL_USER
           valueFrom:
             secretKeyRef:
                name: mysql-user-pass
                key: username
         - name: MYSQL_ROOT_PASSWORD
           valueFrom:
             secretKeyRef:
                name: mysql-root-pass
                key: password
         - name: MYSQL_PASSWORD
           valueFrom:
             secretKeyRef:
                name: mysql-user-pass
                key: password
         - name: MYSQL_HOST
           valueFrom:
             secretKeyRef:
                name: mysql-host
                key: host
         volumeMounts:
         - name: shared-files
           mountPath: /var/www/html
       volumes:
       - name: nginx-persistent-storage
         persistentVolumeClaim:
           claimName: nginx-pv-claim
       - name: shared-files
         emptyDir: {}
       - name: nginx-config-volume
         configMap:
            name: nginx-config
